### ISSUE TITLE
Does the USER_WHITELIST works?

### ISSUE THREAD

**Issue by ITqua** [soyelmismo/chatgpTG#5]
I've tried to add
USER_WHITELIST=123456
to .env file, as well as

- USER_WHITELIST=123456
to docker-compose.yml, but it looks like it's completely ignored, and my bot still answers to any telegram ID.

Could you please provide a working example of the USER_WHITELIST directive?

Thanks.

**Comment by soyelmismo** [comment]
you used it well.

removed chat_whitelist... user_whitelist should work now as expected
