### ISSUE TITLE
The "Text improver" mode doesn't work

### ISSUE THREAD

**Issue by ITqua** [soyelmismo/chatgpTG#7]
There's an error when trying to use "Text Improver" mode.

**Steps to reproduce:**
Select OpenAI API, and any language model (gpt-3.5-turbo, gpt-4, or any other)
Select any interface language
Select "Text improver" mode
Paste any text as an input

**Expected result:**
To get the text with errors fixed and rephrased

**Actual result:**
An unexpected error occurred... If the problem persists, please start a new dialogue using /new
stream_message > openai: send_message: _prepare_request: <count_tokens.putos_tokens> 'TEXTO EDITADO'

![Screenshot_2](https://github.com/soyelmismo/chatgpTG/assets/29717619/afa19cfc-ffba-453a-8afc-000965aafa1e)

Could you please investigate and fix that issue?
Thanks.

**Comment by soyelmismo** [comment]
i cant reproduce this error :( is there any extra error message in the console?

**Comment by ITqua** [comment]
Unfortunately, the console output is the same as in chat.

It is possible to bypass the error by removing the construction {TEXTO EDITADO}, {LISTA NUMERADA DE CORRECCIONES} from the prompt, or just by replacing {} with []. but in this case, the output is not formatted and is not always correct.

I suspect something is wrong with usage of {} or {MARKUP}

 "prompt_start": "Como chatbot avanzado Asistente de Mejora de Texto, mi función es ayudar a corregir errores de ortografía y gramática y mejorar el texto enviado por el usuario. Mi objetivo es editar el texto sin cambiar su significado y, si es necesario, sustituir palabras y frases simplificadas por otras más elegantes y complejas.\n\nTodas mis respuestas siguen estrictamente la estructura (mantendré las etiquetas HTML):\n<b>Texto editado:</b>\n{TEXTO EDITADO}\n\n<b>Correcciones:</b>\n{LISTA NUMERADA DE CORRECCIONES}\n",

**Comment by soyelmismo** [comment]
try removing it and pls notify me

**Comment by ITqua** [comment]
The original build (clone of your repository)
Console response:
![Screenshot_1](https://github.com/soyelmismo/chatgpTG/assets/29717619/8ae5f09b-184b-4bd1-a7eb-e0c3084d1a7c)

The modification:
![Screenshot_3](https://github.com/soyelmismo/chatgpTG/assets/29717619/55ead3c5-546a-4325-b285-65d350763475)

Just {} were replaced with [] in the prompt, nothing else changed.

The results:
![Screenshot_5](https://github.com/soyelmismo/chatgpTG/assets/29717619/64dc810c-0a6b-4b52-8c11-8222e8808bf3)
(looks ok this time)

**Comment by soyelmismo** [comment]
thanks, will add it
